
import React from "react";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { ChevronDown } from "lucide-react";

const TermsOfService = () => {
  return (
    <div className="max-w-4xl mx-auto py-8">
      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
      <p className="text-muted-foreground mb-6">Last updated: {new Date().toLocaleDateString()}</p>
      
      <div className="space-y-6">
        <div className="p-6 bg-card rounded-lg shadow-sm">
          <h2 className="text-xl font-semibold mb-4">Agreement to Terms</h2>
          <p className="mb-4">
            These Terms of Service constitute a legally binding agreement made between you and Aptora, 
            concerning your access to and use of our e-learning platform.
          </p>
          <p>
            By accessing or using Aptora, you agree to be bound by these Terms. If you disagree with any 
            part of the terms, you may not access the platform.
          </p>
        </div>

        <div className="space-y-4">
          <Collapsible className="border rounded-lg overflow-hidden">
            <CollapsibleTrigger className="flex justify-between items-center w-full p-4 text-left font-medium bg-muted/50 hover:bg-muted/80">
              <span>User Rights and Responsibilities</span>
              <ChevronDown className="h-5 w-5 text-muted-foreground transition-transform duration-200 ui-open:rotate-180" />
            </CollapsibleTrigger>
            <CollapsibleContent className="p-4 pt-0 text-sm">
              <div className="pt-4 space-y-2">
                <p className="font-medium">As a user of Aptora, you have the right to:</p>
                <ul className="list-disc pl-5 space-y-1">
                  <li>Access and use the e-learning tools provided on the platform</li>
                  <li>Generate content for educational purposes</li>
                  <li>Receive technical support for platform-related issues</li>
                </ul>
                
                <p className="font-medium mt-4">You are responsible for:</p>
                <ul className="list-disc pl-5 space-y-1">
                  <li>Maintaining the confidentiality of your account credentials</li>
                  <li>Using the platform in compliance with all applicable laws</li>
                  <li>Ensuring that content you generate does not infringe on intellectual property rights</li>
                  <li>Not using the platform to distribute harmful content or engage in unethical activities</li>
                </ul>
              </div>
            </CollapsibleContent>
          </Collapsible>

          <Collapsible className="border rounded-lg overflow-hidden">
            <CollapsibleTrigger className="flex justify-between items-center w-full p-4 text-left font-medium bg-muted/50 hover:bg-muted/80">
              <span>Intellectual Property</span>
              <ChevronDown className="h-5 w-5 text-muted-foreground transition-transform duration-200 ui-open:rotate-180" />
            </CollapsibleTrigger>
            <CollapsibleContent className="p-4 pt-0 text-sm">
              <div className="pt-4 space-y-2">
                <p>
                  The Aptora platform, its original content, features, and functionality are owned by Aptora 
                  and are protected by international copyright, trademark, and other intellectual property laws.
                </p>
                
                <p className="mt-2">
                  Content generated by users through the platform is subject to the following terms:
                </p>
                
                <ul className="list-disc pl-5 space-y-1 mt-2">
                  <li>Users retain rights to content they create using the platform</li>
                  <li>Aptora may use anonymized data from user content to improve the platform</li>
                  <li>Users are responsible for ensuring they have rights to all content input into the system</li>
                </ul>
              </div>
            </CollapsibleContent>
          </Collapsible>

          <Collapsible className="border rounded-lg overflow-hidden">
            <CollapsibleTrigger className="flex justify-between items-center w-full p-4 text-left font-medium bg-muted/50 hover:bg-muted/80">
              <span>Limitation of Liability</span>
              <ChevronDown className="h-5 w-5 text-muted-foreground transition-transform duration-200 ui-open:rotate-180" />
            </CollapsibleTrigger>
            <CollapsibleContent className="p-4 pt-0 text-sm">
              <div className="pt-4 space-y-2">
                <p>
                  In no event shall Aptora, nor its directors, employees, partners, agents, suppliers, or affiliates, 
                  be liable for any indirect, incidental, special, consequential, or punitive damages, including 
                  without limitation, loss of profits, data, use, goodwill, or other intangible losses.
                </p>
                
                <p className="mt-2">
                  Aptora does not warrant that:
                </p>
                
                <ul className="list-disc pl-5 space-y-1 mt-2">
                  <li>The service will be uninterrupted, timely, secure, or error-free</li>
                  <li>The results from using the service will be accurate or reliable</li>
                  <li>The quality of any products, services, information, or other material obtained through the service will meet your expectations</li>
                </ul>
              </div>
            </CollapsibleContent>
          </Collapsible>

          <Collapsible className="border rounded-lg overflow-hidden">
            <CollapsibleTrigger className="flex justify-between items-center w-full p-4 text-left font-medium bg-muted/50 hover:bg-muted/80">
              <span>Termination</span>
              <ChevronDown className="h-5 w-5 text-muted-foreground transition-transform duration-200 ui-open:rotate-180" />
            </CollapsibleTrigger>
            <CollapsibleContent className="p-4 pt-0 text-sm">
              <div className="pt-4 space-y-2">
                <p>
                  We may terminate or suspend your account and bar access to the platform immediately, without prior 
                  notice or liability, under our sole discretion, for any reason whatsoever and without limitation, 
                  including but not limited to a breach of the Terms.
                </p>
                
                <p className="mt-2">
                  If you wish to terminate your account, you may simply discontinue using the platform or contact our 
                  support team to request account deletion.
                </p>
              </div>
            </CollapsibleContent>
          </Collapsible>
        </div>

        <div className="p-6 bg-card rounded-lg shadow-sm">
          <h2 className="text-xl font-semibold mb-4">Contact Us</h2>
          <p>
            If you have any questions about these Terms, please contact us at:
            <br />
            <a href="mailto:legal@aptora.com" className="text-primary hover:underline">
              legal@aptora.com
            </a>
          </p>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
